Switch back to packed_simd dependency
thomwiggers/lpn pull request #39
Opened 2023-09-25 20:27 UTC by atouchet

packed_simd is now again being published under its original name.

2023-09-26 10:58 UTC, thomwiggers approved these changes

2023-09-26 12:32 UTC, thomwiggers commented
Unfortunately, the `rand` crate still relies on `packed_simd_2` and thus still breaks the build. It would also be better to just use `std::simd` directly but that seems like more effort

2023-09-26 12:34 UTC, thomwiggers requested changes
we're also still blocked by `rand`

2023-09-26 12:34 UTC, thomwiggers commented on src/lf1.rs
> -use packed_simd_2::i64x4;
okay we should instead just replace this by `std::simd::i64x4`

2024-04-03 03:39 UTC, atouchet commented
Ah, whoops. It looks like rand is [switching to std::simd](https://github.com/rust-random/rand/pull/1239) but that is waiting on a new release.

2024-04-03 03:39 UTC, closed without merging